[project]
name = "Transcriber"
version = "0.1.0"
description = "A simple tool to transcribe audio files"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.7.1",
    "yt-dlp==2025.1.15",
]
